//import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//  import { ChakraProvider } from '@chakra-ui/react';
//  import { CacheProvider } from '@chakra-ui/next-js';
//  import { theme } from '@/chakra/theme';
//  import Navbar from '../components/Navbar/Navbar';
//  import {RecoilRoot} from "recoil";
import MainClientLayout from '@/components/Layout/MainClientLayout';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Reddit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <RecoilRoot>
        <CacheProvider>
        <ChakraProvider theme={theme}>
        <Navbar/>
        {children}
        </ChakraProvider>
        </CacheProvider>
        </RecoilRoot> */}
        <MainClientLayout>
          {children}
          </MainClientLayout>
        </body>
    </html>
  )
}
